### ISSUE TITLE
Metal support in Resolve

### ISSUE THREAD

**Issue by hateom** [NatronGitHub/openfx#11]
Hello,

Just wanted to ask if there are any plans of including Metal support in this fork (modified OpenFX libs shipped with DaVinci).

**Comment by devernay** [comment]
Any pointers to how we can get these libs?

**Comment by hateom** [comment]
They are installed together with DaVinci Resolve.
On macOS they are in: 
/Library/Application\ Support/Blackmagic\ Design/DaVinci\ Resolve/Developer/OpenFX

I have compressed and uploaded the files here:
https://www.dropbox.com/s/hrbupwcz7r2qe07/ofx_resolve_16.zip?dl=1
