### ISSUE TITLE
What is license of this fork?

### ISSUE THREAD

**Issue by hypernewbie** [NatronGitHub/openfx#13]
Original OpenFX API is BSD 3-clause.
Is this forked repository also BSD 3-clause?

I don't mean the plugins / hosts created with this API, I mean the API library itself, as in this actual repository.

Thanks!

**Comment by rodlie** [comment]
The license has not been changed.

**Comment by hypernewbie** [comment]
Thanks for quick clarification!

**Comment by hypernewbie** [comment]
Oh, one more thing, can the license please be added to the repository in a clear manner?
Eg. as a LICENSE file, which seems to be the standard way of doing things like this on github :)
Thanks!

**Comment by rodlie** [comment]
The license file is located in the Support folder (https://github.com/NatronGitHub/openfx/blob/master/Support/LICENSE).

**Comment by devernay** [comment]
fixed by 1645fd7
