### ISSUE TITLE
Compilation issue on Linux

### ISSUE THREAD

**Issue by elaye** [NatronGitHub/openfx#8]
I'm having an issue compiling `ofxsImageEffect.cpp` on linux. I get this error:

    ../openfx/Support/Library/ofxsImageEffect.cpp:4228:35: error: expected initializer before ‘:’ token
       class LOCAL ActualROISetter : public OFX::RegionOfInterestSetter {
                                   ^

However if I change [this line](https://github.com/devernay/openfx/blob/master/Support/Library/ofxsImageEffect.cpp#L59):

    #if defined __APPLE__ || defined linux || defined __FreeBSD__

to this:

    #if defined __APPLE__ || defined __linux__ || defined __FreeBSD__

it seems to work fine.

**Comment by devernay** [comment]
fixed by https://github.com/NatronGitHub/openfx/commit/2a019f59c233a2f8bef40ecad07473f2cc637805
